version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000

  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    ports:
      - "8000:8000"
  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    environment:
      DYNAMO_ENDPOINT: "dynamodb:8000"
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
